Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # We only want two routes so we’ve added the restriction only: [:new, :create] .
  resource :contacts, only: [:new, :create]

  # The new route has these properties:
  #                             • new_contact_path – route helper
  # • contacts – name of the controller (ContactsController)
  # • new – controller action
  # • http://localhost:3000/contacts/new – URL generated by the route helper
  # • GET – HTTP method to display a page

  # The create route has these properties:
  # • contacts_path – route helper
  # • contacts – name of the controller (ContactsController)
  # • create – controller action
  # • http://localhost:3000/contacts – URL generated by the route helper
  # • POST – HTTP method to submit form data



  # resource :visitors
  # post 'contact', to: 'contacts#process_form'
  root 'visitors#new'
end
